<?xml version="1.0" encoding="utf-8"?><definitions name="tacService" targetNamespace="http://j2ee.netbeans.org/wsdl/tacService" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://xml.netbeans.org/schema/tacService" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://j2ee.netbeans.org/wsdl/tacService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/tacService">
            <xsd:import namespace="http://xml.netbeans.org/schema/tacService" schemaLocation="tacService.xsd"/>
        </xsd:schema>
    </types>
    <message name="reverseLinesRequest">
        <part element="ns:tacRequest" name="request"/>
    </message>
    <message name="reverseLinesResponse">
        <part element="ns:tacResponse" name="response"/>
    </message>
    <portType name="tacServicePortType">
        <operation name="reverseLines">
            <input message="tns:reverseLinesRequest" name="input1"/>
            <output message="tns:reverseLinesResponse" name="output1"/>
        </operation>
    </portType>
    <binding name="tacServiceBinding" type="tns:tacServicePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="reverseLines">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="tacService">
        <port binding="tns:tacServiceBinding" name="tacServicePort">
            <soap:address location="http://localhost:8080/active-bpel/services/tacService"/>
        </port>
    </service>
    <plnk:partnerLinkType name="tacService">
        <plnk:role name="tacServicePortTypeRole" portType="tns:tacServicePortType"/>
    </plnk:partnerLinkType>
</definitions>